locals {
  location                          = "japaneast"
  resource_group_name               = "udemy_resource_group"
  vnet_name                         = "udemy_virtual_network"
  public_subnet_name                = "public"
  private_subnet_name               = "private"
  vm_network_interface              = "udemy_network_interface"
  vm_security_group                 = "udemy_security_group"
  vm_name                           = "udemy-vm"
  vm_admin_username                 = "adminuser"
  vm_admin_password                 = "P@$$w0rd1234!"
  bastion_public_ip                 = "udemy-bastion-public-ip"
  bastion_host_name                 = "udemy-bastion"
  lb_public_ip_name                 = "udemy-lb-public-ip"
  lb_name                           = "udemy-lb"
  lb_backend_pool_name              = "udemy-lb-backend-pool"
  lb_rule_name                      = "udemy-lb-rule"
  sql_server_name                   = "udemy-sqlserver-server"
  sql_server_administrator_login    = "sqladministrator"
  sql_server_administrator_password = "P@$$w0rd1234!"
  sql_firewall_rule_name            = "udemy-sql-firewall-rule"
  sql_database_name                 = "udemy-sqlserver-database"
  sql_virtual_network_rule_name     = "udemy-sql-virtual-network-rule"
}
